// src/svelte/components/modal/ModalInner.svelte
<script lang="ts">  import { onMount, setContext } from 'svelte';
  import type { Snippet } from 'svelte';
  import type { BaseModalProps, ExternalElementProps } from '../../../core/types';
  import { MODAL_ID_CONTEXT } from '../../context';
  import { ModalController, type ComputedModalState } from '../../../core/modal';
  import { bringToFront } from '../../../core/state';
  import { getReactiveConfigVersion } from '../../stores.svelte';
  import { CSS, DATA_ATTRS } from '../../../core/utils/constants';
  import { toDataId } from '../../../core/utils/helpers';

  import Portal from '../Portal.svelte';
  import ModalHeader from './ModalHeader.svelte';
  import ResizeHandles from './ResizeHandles.svelte';

  import { appendElement } from '../../actions/appendElement';

  import { useModalConfig } from '../../hooks/useModalConfig.svelte';

  interface ModalComponentProps extends BaseModalProps, ExternalElementProps {

    customIcon?: Snippet;

    providerConfig?: Partial<import('../../../core/config').ModalLibraryConfig>;

    children?: Snippet;

    footer?: Snippet;

    skipRegistration?: boolean;
  }

  let {
    id,
    title,
    customIcon,
    icon,
    iconElement,
    description,
    maxWidth = '600px',
    preferredHeight,
    autoOpen = false,
    openSourcePosition: propOpenSourcePosition,
    glow,
    config: modalConfig,
    providerConfig,
    closeOnEscape = true,
    onClose,
    children,
    footer,
    skipRegistration = false,
    bodyElement,
    footerElement,
  }: ModalComponentProps = $props();

  setContext(MODAL_ID_CONTEXT, () => id);

  const configHelper = useModalConfig({
    getModalConfig: () => modalConfig,
    getProviderConfig: () => providerConfig,
  });

  const portalTarget = $derived.by(() => {
    return configHelper.getEffectiveConfig().portalTarget;
  });

  let controller: ModalController | null = $state(null);
  let computedState: ComputedModalState | null = $state(null);
  let modalEl: HTMLElement | null = $state(null);

  onMount(() => {
    controller = new ModalController({
      id,
      title,
      icon,
      config: modalConfig,
      providerConfig,
      maxWidth,
      preferredHeight,
      glow,
      closeOnEscape,
      autoOpen,
      openSourcePosition: propOpenSourcePosition,
      onClose,
      skipRegistration,
      configHelper,
    });

    const unsubscribe = controller.subscribe((newState) => {
      computedState = newState;
    });

    computedState = controller.getState();

    return () => {
      unsubscribe();
      controller?.destroy();
      controller = null;
    };
  });

  $effect(() => {
    if (modalEl && controller) {
      controller.mount(modalEl);
    }
  });

  $effect(() => {
    if (controller && propOpenSourcePosition !== undefined) {
      controller.setOpenSourcePosition(propOpenSourcePosition);
    }
  });

  $effect(() => {
    if (controller) {
      controller.updateOptions({ glow, maxWidth, preferredHeight, closeOnEscape });
    }
  });

  const dataId = $derived(toDataId(id));
  const titleId = $derived(`modal-title-${dataId}`);
  const descriptionId = $derived(description ? `modal-desc-${dataId}` : undefined);

  const draggable = $derived((computedState as ComputedModalState | null)?.draggable ?? false);
  const resizable = $derived((computedState as ComputedModalState | null)?.resizable ?? false);
  const minimizable = $derived((computedState as ComputedModalState | null)?.minimizable ?? false);
  const minimizeDisabled = $derived.by(() => {
    getReactiveConfigVersion();
    return !configHelper.isFeatureEnabled('dock');
  });
  const transparencyEnabled = $derived.by(() => {
    getReactiveConfigVersion();
    return configHelper.isFeatureEnabled('transparency');
  });
  const headerLayout = $derived.by(() => {
    getReactiveConfigVersion();
    return configHelper.getAppearance('headerLayout');
  });

  const isVisible = $derived((computedState as ComputedModalState | null)?.isVisible ?? false);
  const showOverlay = $derived((computedState as ComputedModalState | null)?.showOverlay ?? false);
  const overlayClosing = $derived((computedState as ComputedModalState | null)?.overlayClosing ?? false);
  const isTransparent = $derived((computedState as ComputedModalState | null)?.isTransparent ?? false);

  const modalStyle = $derived.by(() => {
    const s = computedState as ComputedModalState | null;
    if (!s) return '';
    return Object.entries(s.style)
      .map(([key, value]) => `${key}: ${value};`)
      .join(' ');
  });

  function handleDragStart(e: PointerEvent) {
    controller?.startDrag(e);
  }

  function handlePointerMove(e: PointerEvent) {
    controller?.handlePointerMove(e);
  }

  function handlePointerUp(e: PointerEvent) {
    controller?.handlePointerUp(e);
  }

  function handleKeyDown(e: KeyboardEvent) {
    controller?.handleKeyDown(e);
  }

  function handleMinimize() {
    controller?.minimize();
  }

  function handleClose() {
    controller?.close();
  }

  function handleToggleStyle() {
    controller?.toggleTransparency();
  }

  function handleResizeStart(e: PointerEvent, direction: import('../../../core/behaviors/resize').ResizeDirection) {
    controller?.startResize(e, direction);
  }
</script>

{#if isVisible && computedState}
  <Portal target={portalTarget}>
    <div
      bind:this={modalEl}
      class={computedState.cssClasses.join(' ')}
      {...{[DATA_ATTRS.modalId]: dataId}}
      data-state={computedState.dataState}
      data-animation-phase={computedState.dataAnimationPhase}
      style={modalStyle}
      role="dialog"
      aria-modal="true"
      aria-labelledby={titleId}
      aria-describedby={descriptionId}
      tabindex="-1"
      onkeydown={handleKeyDown}
      onpointermove={handlePointerMove}
      onpointerup={handlePointerUp}
      onpointerdowncapture={() => bringToFront(id)}
    >
      {#if description}
        <span id={descriptionId} class="sr-only">{description}</span>
      {/if}

      <ModalHeader
        title={title}
        customIcon={customIcon}
        icon={icon}
        iconElement={iconElement}
        isTransparent={isTransparent}
        titleId={titleId}
        headerLayout={headerLayout}
        onStartDrag={draggable ? handleDragStart : undefined}
        onToggleStyle={handleToggleStyle}
        onMinimize={handleMinimize}
        onClose={handleClose}
        minimizable={minimizable}
        minimizeDisabled={minimizeDisabled}
        transparencyEnabled={transparencyEnabled}
      />

      <div class={CSS.body} use:appendElement={bodyElement}>
        {@render children?.()}
      </div>

      {#if footer || footerElement}
        <div class={CSS.footer} use:appendElement={footerElement}>
          {#if footer}
            {@render footer()}
          {/if}
        </div>
      {/if}

      <ResizeHandles onStartResize={resizable && !computedState.hasChild ? handleResizeStart : undefined} />

      {#if showOverlay}
        <div class={CSS.childOverlay} class:modal-overlay-closing={overlayClosing}></div>
      {/if}
    </div>
  </Portal>
{/if}

// src/react/components/modal/ModalInner.tsx
import React, {
  useRef,
  useState,
  useEffect,
  useCallback,
  useContext,
  useMemo,
  type ReactNode,
  type KeyboardEvent as ReactKeyboardEvent,
  type PointerEvent as ReactPointerEvent,
} from 'react';
import type { BaseModalProps } from '../../../core/types';
import type { ModalLibraryConfig } from '../../../core/config';
import type { ResizeDirection } from '../../../core/behaviors/resize';
import { CSS } from '../../../core/utils/constants';
import { toDataId } from '../../../core/utils/helpers';
import { ModalController, type ComputedModalState } from '../../../core/modal';
import { bringToFront, isTopModal } from '../../../core/state';
import { Portal } from '../Portal';
import { ModalHeader } from './ModalHeader';
import { ResizeHandles } from './ResizeHandles';
import { useModalConfig } from '../../hooks/useConfig';
import { ModalProviderConfigContext, ModalIdContext } from '../../context';

function kebabToCamelCase(str: string): string {
  return str.replace(/-([a-z])/g, (_, letter) => letter.toUpperCase());
}

function toReactStyle(style: Record<string, string | number>): React.CSSProperties {
  const result: Record<string, string | number> = {};
  for (const [key, value] of Object.entries(style)) {

    if (key.startsWith('--')) {
      result[key] = value;
    } else {
      result[kebabToCamelCase(key)] = value;
    }
  }
  return result as React.CSSProperties;
}

export interface ModalInnerProps extends BaseModalProps {

  renderIcon?: () => ReactNode;

  providerConfig?: Partial<ModalLibraryConfig>;

  children?: ReactNode;

  footer?: ReactNode;

  skipRegistration?: boolean;
}

const INITIAL_STATE: ComputedModalState = {
  position: { x: 0, y: 0 },
  size: { width: 0, height: 0 },
  zIndex: 1000,
  isDragging: false,
  isResizing: false,
  hasBeenDragged: false,
  hasBeenResized: false,
  isMinimizing: false,
  isRestoring: false,
  isOpening: false,
  isClosing: false,
  isAnyAnimating: false,
  animationTransform: null,
  isVisible: false,
  showCentered: false,
  isAwaitingRestore: false,
  isAwaitingChildOpen: false,
  isVisibleByAnimation: false,
  hasChild: false,
  isChildModal: false,
  showOverlay: false,
  isTransparent: false,
  isAttentionAnimating: false,
  glowStabilizing: false,
  isAnimatingPosition: false,
  isAnimatingToCenter: false,
  wasRestored: false,
  overlayClosing: false,
  glowEnabled: false,
  draggable: true,
  resizable: true,
  minimizable: true,
  dataState: 'closed',
  dataAnimationPhase: 'none',
  style: {},
  cssClasses: [CSS.modal],
};

export function ModalInner({
  id,
  title,
  renderIcon,
  icon,
  description,
  maxWidth = '600px',
  preferredHeight,
  autoOpen = false,
  openSourcePosition: propOpenSourcePosition,
  glow,
  config: modalConfig,
  providerConfig: propProviderConfig,
  closeOnEscape = true,
  onClose,
  children,
  footer,
  skipRegistration = false,
}: ModalInnerProps) {

  const modalRef = useRef<HTMLDivElement>(null);
  const controllerRef = useRef<ModalController | null>(null);

  const contextProviderConfig = useContext(ModalProviderConfigContext);
  const providerConfig = propProviderConfig ?? contextProviderConfig;

  const configHelper = useModalConfig({
    modalConfig,
  });

  const portalTarget = configHelper.getEffectiveConfig().portalTarget;
  const minimizeDisabled = !configHelper.isFeatureEnabled('dock');
  const transparencyEnabled = configHelper.isFeatureEnabled('transparency');
  const headerLayout = configHelper.getAppearance('headerLayout');

  const [state, setState] = useState<ComputedModalState>(INITIAL_STATE);

  const dataId = toDataId(id);
  const titleId = `modal-title-${dataId}`;
  const descriptionId = description ? `modal-desc-${dataId}` : undefined;

  useEffect(() => {
    const controller = new ModalController({
      id,
      title,
      icon,
      config: modalConfig,
      providerConfig,
      maxWidth,
      preferredHeight,
      glow,
      closeOnEscape,
      autoOpen,
      openSourcePosition: propOpenSourcePosition,
      onClose,
      skipRegistration,
      configHelper,
    });
    controllerRef.current = controller;

    const unsubscribe = controller.subscribe((newState) => {
      setState(newState);
    });

    setState(controller.getState());

    return () => {
      unsubscribe();
      controller.destroy();
      controllerRef.current = null;
    };
  }, [id]);

  useEffect(() => {
    if (modalRef.current && controllerRef.current && state.isVisible) {
      controllerRef.current.mount(modalRef.current);
    }
  }, [state.isVisible]);

  useEffect(() => {
    controllerRef.current?.updateOptions({ glow, maxWidth, preferredHeight, closeOnEscape });
  }, [glow, maxWidth, preferredHeight, closeOnEscape]);

  const isVisibleRef = useRef(state.isVisible);
  isVisibleRef.current = state.isVisible;

  useEffect(() => {
    if (!closeOnEscape) return;

    const handleGlobalEscape = (e: globalThis.KeyboardEvent) => {
      if (e.key !== 'Escape') return;

      if (!isVisibleRef.current) return;

      if ((e as unknown as { _modalEscapeHandled?: boolean })._modalEscapeHandled) return;

      if (controllerRef.current && isTopModal(id)) {
        controllerRef.current.handleKeyDown(e);

        (e as unknown as { _modalEscapeHandled?: boolean })._modalEscapeHandled = true;
      }
    };

    document.addEventListener('keydown', handleGlobalEscape, true);
    return () => document.removeEventListener('keydown', handleGlobalEscape, true);
  }, [closeOnEscape, id]);

  useEffect(() => {
    if (controllerRef.current && propOpenSourcePosition !== undefined) {
      controllerRef.current.setOpenSourcePosition(propOpenSourcePosition);
    }
  }, [propOpenSourcePosition]);

  const handleDragStart = useCallback((e: ReactPointerEvent) => {
    controllerRef.current?.startDrag(e.nativeEvent);
  }, []);

  const handlePointerMove = useCallback((e: ReactPointerEvent) => {
    controllerRef.current?.handlePointerMove(e.nativeEvent);
  }, []);

  const handlePointerUp = useCallback((e: ReactPointerEvent) => {
    controllerRef.current?.handlePointerUp(e.nativeEvent);
  }, []);

  const handleKeyDown = useCallback((e: ReactKeyboardEvent) => {
    controllerRef.current?.handleKeyDown(e.nativeEvent);
  }, []);

  const handleMinimize = useCallback(() => {
    controllerRef.current?.minimize();
  }, []);

  const handleClose = useCallback(() => {
    controllerRef.current?.close();
  }, []);

  const handleToggleStyle = useCallback(() => {
    controllerRef.current?.toggleTransparency();
  }, []);

  const handleResizeStart = useCallback((e: React.PointerEvent, direction: ResizeDirection) => {
    controllerRef.current?.startResize(e.nativeEvent, direction);
  }, []);

  const reactStyle = useMemo(() => toReactStyle(state.style), [state.style]);

  if (!state.isVisible) {
    return null;
  }

  return (
    <Portal target={portalTarget}>
      <ModalIdContext.Provider value={id}>
        <div
          ref={modalRef}
          className={state.cssClasses.join(' ')}
          data-modal-id={dataId}
          data-state={state.dataState}
          data-animation-phase={state.dataAnimationPhase}
          style={reactStyle}
          role="dialog"
          aria-modal="true"
          aria-labelledby={titleId}
          aria-describedby={descriptionId}
          tabIndex={-1}
          onKeyDown={handleKeyDown}
          onPointerMove={handlePointerMove}
          onPointerUp={handlePointerUp}
          onPointerDownCapture={() => bringToFront(id)}
        >
          {description && (
            <span id={descriptionId} className="sr-only">{description}</span>
          )}

          <ModalHeader
            title={title}
            customIcon={renderIcon?.()}
            icon={icon}
            isTransparent={state.isTransparent}
            titleId={titleId}
            headerLayout={headerLayout}
            onStartDrag={state.draggable ? handleDragStart : undefined}
            onToggleStyle={handleToggleStyle}
            onMinimize={handleMinimize}
            onClose={handleClose}
            minimizable={state.minimizable}
            minimizeDisabled={minimizeDisabled}
            transparencyEnabled={transparencyEnabled}
          />

          <div className={CSS.body}>
            {children}
          </div>

          {footer && (
            <div className={CSS.footer}>
              {footer}
            </div>
          )}

          <ResizeHandles
            onStartResize={state.resizable && !state.hasChild ? handleResizeStart : undefined}
          />

          {state.showOverlay && (
            <div
              className={`${CSS.childOverlay}${state.overlayClosing ? ` ${CSS.overlayClosing}` : ''}`}
            />
          )}
        </div>
      </ModalIdContext.Provider>
    </Portal>
  );
}
