// src/svelte/components/modal/Modal.svelte
<script lang="ts">  import { onMount, onDestroy } from 'svelte';
  import type { Snippet } from 'svelte';
  import type { BaseModalProps, ExternalElementProps } from '../../../core/types';
  import {
    registerModal,
    unregisterModal,
    createModalRegistration,
  } from '../../../core/state/registration';
  import {
    getModalState,
    hasPendingOpen,
    hasPendingClose,
    hasPendingMinimize,
  } from '../../../core/state';
  import { getReactiveStateVersion } from '../../stores.svelte';
  import ModalInner from './ModalInner.svelte';

  interface ModalComponentProps extends BaseModalProps, ExternalElementProps {

    customIcon?: Snippet;
    children?: Snippet;
    footer?: Snippet;
  }

  let {
    id,
    title,
    icon,
    customIcon,
    iconElement,
    maxWidth = '600px',
    preferredHeight,
    autoOpen = false,
    openSourcePosition,
    glow,
    config,
    closeOnEscape = true,
    onClose,
    children,
    footer,
    bodyElement,
    footerElement,
  }: ModalComponentProps = $props();

  let isRegistered = $state(false);

  onMount(() => {
    registerModal(createModalRegistration({ id, title, icon, autoOpen, glow }));
    isRegistered = true;
  });

  onDestroy(() => {

    const state = getModalState(id);
    if (state?.isHiddenWithParent) return;

    unregisterModal(id);
  });

  const shouldMount = $derived.by(() => {
    if (!isRegistered) return false;

    getReactiveStateVersion();
    const state = getModalState(id);

    if (!state) return false;

    return state.isOpen ||
           state.isMinimized ||
           hasPendingOpen(id) ||
           hasPendingClose(id) ||
           hasPendingMinimize(id);
  });
</script>

{#if shouldMount}
  <ModalInner
    {id}
    {title}
    {icon}
    {customIcon}
    {iconElement}
    {maxWidth}
    {preferredHeight}
    {autoOpen}
    {openSourcePosition}
    {glow}
    {config}
    {closeOnEscape}
    {onClose}
    {children}
    {footer}
    {bodyElement}
    {footerElement}
    skipRegistration={true}
  />
{/if}

// src/react/components/modal/Modal.tsx
import React, { useEffect, useContext, type ReactNode } from 'react';
import type { BaseModalProps } from '../../../core/types';
import {
  registerModal,
  unregisterModal,
  createModalRegistration,
} from '../../../core/state/registration';
import { bringToFront, getModalState } from '../../../core/state';
import { ModalInner } from './ModalInner';
import { ModalProviderConfigContext, RenderIconContext } from '../../context';

export interface ModalProps extends BaseModalProps {
  children?: ReactNode;
  footer?: ReactNode;

  renderIcon?: () => ReactNode;
}

export function Modal({
  id,
  title,
  icon,
  maxWidth = '600px',
  preferredHeight,
  autoOpen = false,
  glow,
  config,
  closeOnEscape = true,
  onClose,
  children,
  footer,
  renderIcon,
}: ModalProps) {

  const providerConfig = useContext(ModalProviderConfigContext);
  const contextRenderIcon = useContext(RenderIconContext);

  useEffect(() => {
    registerModal(createModalRegistration({ id, title, icon, autoOpen, glow }));

    if (autoOpen) {
      bringToFront(id);
    }

    return () => {

      const state = getModalState(id);
      if (state?.isHiddenWithParent) return;

      unregisterModal(id);
    };
  }, [id]);

  const iconRenderer = renderIcon ?? (icon && contextRenderIcon ? () => contextRenderIcon(icon) : undefined);

  return (
    <ModalInner
      id={id}
      title={title}
      icon={icon}
      renderIcon={iconRenderer}
      maxWidth={maxWidth}
      preferredHeight={preferredHeight}
      autoOpen={autoOpen}
      glow={glow}
      config={config}
      providerConfig={providerConfig ?? undefined}
      closeOnEscape={closeOnEscape}
      onClose={onClose}
      skipRegistration={true}
      footer={footer}
    >
      {children}
    </ModalInner>
  );
}
