// src/svelte/components/Backdrop.svelte
<script lang="ts">  import { fade } from 'svelte/transition';
  import { getConfig } from '../../core/config';
  import { getLayerZIndex } from '../../core/state/parent-child';
  import { getReactiveStateVersion, getReactiveConfigVersion } from '../stores.svelte';
  import { hasOpenModals, isBackdropEnabled, getBackdropConfig } from '../../core/utils/backdrop';
  import Portal from './Portal.svelte';
  import { CSS } from '../../core/utils/constants';

  const config = $derived.by(() => {
    getReactiveConfigVersion();
    return getConfig();
  });

  const backdropConfig = $derived.by(() => {
    getReactiveConfigVersion();
    return getBackdropConfig();
  });

  const backdropEnabled = $derived.by(() => {
    getReactiveConfigVersion();
    return isBackdropEnabled();
  });

  const hasOpenModal = $derived.by(() => {
    getReactiveStateVersion();
    return hasOpenModals();
  });

  const backdropZIndex = $derived(getLayerZIndex('MODAL') - 1);
</script>

<Portal target={config.portalTarget}>
  {#if hasOpenModal && backdropEnabled}
    <div
      class={CSS.backdrop}
      class:backdrop-visible={backdropConfig.visible}
      class:backdrop-blocking={backdropConfig.blockClicks}
      style:z-index={backdropZIndex}
      transition:fade={{ duration: 200 }}
      aria-hidden="true"
    ></div>
  {/if}
</Portal>

// src/react/components/Backdrop.tsx
import React, { useContext, useEffect, useState } from 'react';
import { Portal } from './Portal';
import { ModalProviderConfigContext } from '../context';
import { CSS } from '../../core/utils/constants';
import { getConfig, subscribeToConfig } from '../../core/config';
import { subscribe } from '../../core/state';
import { getLayerZIndex } from '../../core/state/parent-child';
import { hasOpenModals, isBackdropEnabled, getBackdropConfig } from '../../core/utils/backdrop';

export interface BackdropProps {

  className?: string;
}

export function Backdrop({ className }: BackdropProps) {
  const providerConfig = useContext(ModalProviderConfigContext);
  const [, forceUpdate] = useState(0);

  useEffect(() => {
    const unsub1 = subscribe(() => {
      forceUpdate((n) => n + 1);
    });
    const unsub2 = subscribeToConfig(() => {
      forceUpdate((n) => n + 1);
    });
    return () => { unsub1(); unsub2(); };
  }, []);

  const globalConfig = getConfig();
  const portalTarget = providerConfig?.portalTarget ?? globalConfig.portalTarget;

  const backdropEnabled = isBackdropEnabled();
  const backdropConfig = getBackdropConfig();
  const hasOpenModal = hasOpenModals();

  const backdropZIndex = getLayerZIndex('MODAL') - 1;

  if (!backdropEnabled || !hasOpenModal) {
    return null;
  }

  const classes = [
    CSS.backdrop,
    backdropConfig.visible && 'backdrop-visible',
    backdropConfig.blockClicks && 'backdrop-blocking',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <Portal target={portalTarget}>
      <div
        className={classes}
        style={{ zIndex: backdropZIndex }}
        aria-hidden="true"
      />
    </Portal>
  );
}
